// Generated by scripts/generate-runtime.mjs. Do not edit by hand.
import asset0_22 from "../shared/border.png?url"
import asset0_69 from "../shared/fonts/DFP-ReiSho-W6-JAJWA.woff?url"
import asset0_65 from "../shared/fonts/ITCStoneSerifMedium.woff2?url"
import asset0_66 from "../shared/fonts/ITCStoneSerifMediumItalic.woff2?url"
import asset0_67 from "../shared/fonts/ITCStoneSerifStdBold.woff2?url"
import asset0_70 from "../shared/fonts/MatrixBoldSmallCaps.woff2?url"
import asset0_71 from "../shared/fonts/MatrixBook.woff2?url"
import asset0_72 from "../shared/fonts/MatrixRegularSmallCaps.woff2?url"
import asset0_73 from "../shared/fonts/RoGSanSrfStd-Bd.otf?url"
import asset0_74 from "../shared/fonts/Stone Serif ITC Semi.ttf?url"
import asset0_68 from "../shared/fonts/Stone Serif ITC TT Small Caps Bold.ttf?url"
import asset0_24 from "../shared/frame-texture.png?url"
import asset0_42 from "../shared/link-texture.png?url"
import asset0_10 from "../shared/pendulum-scale-left.png?url"
import asset0_11 from "../shared/pendulum-scale-right.png?url"
import asset0_43 from "../shared/xyz-texture.png?url"
import asset0_12 from "../templates/card/series-10/assets/artwork-box.png?url"
import asset0_0 from "../templates/card/series-10/assets/artwork-mask.png?url"
import asset0_13 from "../templates/card/series-10/assets/attribute-dark.png?url"
import asset0_15 from "../templates/card/series-10/assets/attribute-earth.png?url"
import asset0_16 from "../templates/card/series-10/assets/attribute-fire.png?url"
import asset0_14 from "../templates/card/series-10/assets/attribute-light-divine.png?url"
import asset0_17 from "../templates/card/series-10/assets/attribute-light-divine.png?url"
import asset0_18 from "../templates/card/series-10/assets/attribute-spell.png?url"
import asset0_19 from "../templates/card/series-10/assets/attribute-trap.png?url"
import asset0_20 from "../templates/card/series-10/assets/attribute-water.png?url"
import asset0_21 from "../templates/card/series-10/assets/attribute-wind.png?url"
import asset0_23 from "../templates/card/series-10/assets/effects-border.png?url"
import asset0_26 from "../templates/card/series-10/assets/link-arrow-active-bottom-center.png?url"
import asset0_27 from "../templates/card/series-10/assets/link-arrow-active-bottom-left.png?url"
import asset0_28 from "../templates/card/series-10/assets/link-arrow-active-bottom-right.png?url"
import asset0_29 from "../templates/card/series-10/assets/link-arrow-active-left-center.png?url"
import asset0_30 from "../templates/card/series-10/assets/link-arrow-active-right-center.png?url"
import asset0_31 from "../templates/card/series-10/assets/link-arrow-active-top-center.png?url"
import asset0_32 from "../templates/card/series-10/assets/link-arrow-active-top-left.png?url"
import asset0_33 from "../templates/card/series-10/assets/link-arrow-active-top-right.png?url"
import asset0_34 from "../templates/card/series-10/assets/link-arrow-inactive-bottom-center.png?url"
import asset0_35 from "../templates/card/series-10/assets/link-arrow-inactive-bottom-left.png?url"
import asset0_36 from "../templates/card/series-10/assets/link-arrow-inactive-bottom-right.png?url"
import asset0_37 from "../templates/card/series-10/assets/link-arrow-inactive-left-center.png?url"
import asset0_38 from "../templates/card/series-10/assets/link-arrow-inactive-right-center.png?url"
import asset0_39 from "../templates/card/series-10/assets/link-arrow-inactive-top-center.png?url"
import asset0_40 from "../templates/card/series-10/assets/link-arrow-inactive-top-left.png?url"
import asset0_41 from "../templates/card/series-10/assets/link-arrow-inactive-top-right.png?url"
import asset0_25 from "../templates/card/series-10/assets/link-arrows-mask.png?url"
import asset0_1 from "../templates/card/series-10/assets/pendulum-artwork-mask.png?url"
import asset0_9 from "../templates/card/series-10/assets/pendulum-border-large.png?url"
import asset0_8 from "../templates/card/series-10/assets/pendulum-border-medium.png?url"
import asset0_7 from "../templates/card/series-10/assets/pendulum-border-small.png?url"
import asset0_5 from "../templates/card/series-10/assets/pendulum-effect-mask-large.svg?url"
import asset0_6 from "../templates/card/series-10/assets/pendulum-effect-mask-large-lower.svg?url"
import asset0_4 from "../templates/card/series-10/assets/pendulum-effect-mask-medium.svg?url"
import asset0_3 from "../templates/card/series-10/assets/pendulum-effect-mask-small.svg?url"
import asset0_2 from "../templates/card/series-10/assets/pendulum-frame-bottom-mask.png?url"
import asset0_44 from "../templates/card/series-10/assets/spell-trap-icon-continuous.png?url"
import asset0_45 from "../templates/card/series-10/assets/spell-trap-icon-counter.png?url"
import asset0_46 from "../templates/card/series-10/assets/spell-trap-icon-equip.png?url"
import asset0_47 from "../templates/card/series-10/assets/spell-trap-icon-field.png?url"
import asset0_48 from "../templates/card/series-10/assets/spell-trap-icon-quick-play.png?url"
import asset0_49 from "../templates/card/series-10/assets/spell-trap-icon-ritual.png?url"
import asset0_50 from "../templates/card/series-10/assets/star-level.png?url"
import asset0_51 from "../templates/card/series-10/assets/star-rank.png?url"
import asset0_52 from "../templates/card/series-10/assets/sticker-00.png?url"
import asset0_53 from "../templates/card/series-10/assets/sticker-01.png?url"
import asset0_54 from "../templates/card/series-10/assets/sticker-02.png?url"
import asset0_55 from "../templates/card/series-10/assets/sticker-03.png?url"
import asset0_56 from "../templates/card/series-10/assets/sticker-04.png?url"
import asset0_57 from "../templates/card/series-10/assets/sticker-05.png?url"
import asset0_58 from "../templates/card/series-10/assets/sticker-06.png?url"
import asset0_59 from "../templates/card/series-10/assets/sticker-07.png?url"
import asset0_60 from "../templates/card/series-10/assets/sticker-08.png?url"
import asset0_61 from "../templates/card/series-10/assets/sticker-09.png?url"
import asset0_62 from "../templates/card/series-10/assets/sticker-10.png?url"
import asset0_63 from "../templates/card/series-10/assets/sticker-11.png?url"
import asset0_64 from "../templates/card/series-10/assets/sticker-12.png?url"
import presets0 from "../templates/card/series-10/color-presets.json"

import runtimeManifests from "./generated-runtime-manifests.json"
import runtimeTemplates from "./generated-runtime-templates.json"

export const generatedDefaultTemplateIds = { card: "card/series-10" } as const

export const generatedTemplateEntries = [
  {
    assets: {
      "card.series-10.artwork-mask": asset0_0,
      "card.series-10.pendulum-artwork-mask": asset0_1,
      "card.series-10.pendulum-frame-mask.spell": asset0_2,
      "card.series-10.pendulum-effect-mask.small": asset0_3,
      "card.series-10.pendulum-effect-mask.medium": asset0_4,
      "card.series-10.pendulum-effect-mask.large": asset0_5,
      "card.series-10.pendulum-effect-mask.large-lower": asset0_6,
      "card.series-10.pendulum-border.small": asset0_7,
      "card.series-10.pendulum-border.medium": asset0_8,
      "card.series-10.pendulum-border.large": asset0_9,
      "card.series-10.pendulum-scale.left": asset0_10,
      "card.series-10.pendulum-scale.right": asset0_11,
      "card.series-10.artwork-box": asset0_12,
      "card.series-10.attribute.dark": asset0_13,
      "card.series-10.attribute.divine": asset0_14,
      "card.series-10.attribute.earth": asset0_15,
      "card.series-10.attribute.fire": asset0_16,
      "card.series-10.attribute.light": asset0_17,
      "card.series-10.attribute.spell": asset0_18,
      "card.series-10.attribute.trap": asset0_19,
      "card.series-10.attribute.water": asset0_20,
      "card.series-10.attribute.wind": asset0_21,
      "card.series-10.border": asset0_22,
      "card.series-10.effects-border": asset0_23,
      "card.series-10.frame-texture": asset0_24,
      "card.series-10.link-arrows-mask": asset0_25,
      "card.series-10.link-arrow.active.bottom-center": asset0_26,
      "card.series-10.link-arrow.active.bottom-left": asset0_27,
      "card.series-10.link-arrow.active.bottom-right": asset0_28,
      "card.series-10.link-arrow.active.left-center": asset0_29,
      "card.series-10.link-arrow.active.right-center": asset0_30,
      "card.series-10.link-arrow.active.top-center": asset0_31,
      "card.series-10.link-arrow.active.top-left": asset0_32,
      "card.series-10.link-arrow.active.top-right": asset0_33,
      "card.series-10.link-arrow.inactive.bottom-center": asset0_34,
      "card.series-10.link-arrow.inactive.bottom-left": asset0_35,
      "card.series-10.link-arrow.inactive.bottom-right": asset0_36,
      "card.series-10.link-arrow.inactive.left-center": asset0_37,
      "card.series-10.link-arrow.inactive.right-center": asset0_38,
      "card.series-10.link-arrow.inactive.top-center": asset0_39,
      "card.series-10.link-arrow.inactive.top-left": asset0_40,
      "card.series-10.link-arrow.inactive.top-right": asset0_41,
      "card.series-10.link-texture": asset0_42,
      "card.series-10.xyz-texture": asset0_43,
      "card.series-10.spell-trap.icon.continuous": asset0_44,
      "card.series-10.spell-trap.icon.counter": asset0_45,
      "card.series-10.spell-trap.icon.equip": asset0_46,
      "card.series-10.spell-trap.icon.field": asset0_47,
      "card.series-10.spell-trap.icon.quick-play": asset0_48,
      "card.series-10.spell-trap.icon.ritual": asset0_49,
      "card.series-10.star.level": asset0_50,
      "card.series-10.star.rank": asset0_51,
      "card.series-10.sticker.00": asset0_52,
      "card.series-10.sticker.01": asset0_53,
      "card.series-10.sticker.02": asset0_54,
      "card.series-10.sticker.03": asset0_55,
      "card.series-10.sticker.04": asset0_56,
      "card.series-10.sticker.05": asset0_57,
      "card.series-10.sticker.06": asset0_58,
      "card.series-10.sticker.07": asset0_59,
      "card.series-10.sticker.08": asset0_60,
      "card.series-10.sticker.09": asset0_61,
      "card.series-10.sticker.10": asset0_62,
      "card.series-10.sticker.11": asset0_63,
      "card.series-10.sticker.12": asset0_64,
      "font.itc-stone-serif-medium": asset0_65,
      "font.itc-stone-serif-medium-italic": asset0_66,
      "font.itc-stone-serif-std-bold": asset0_67,
      "font.stone-serif-itc-tt-sc-bold": asset0_68,
      "font.dfp-reisho-w6-jajwa": asset0_69,
      "font.matrix-bold-small-caps": asset0_70,
      "font.matrix-book": asset0_71,
      "font.matrix-regular-small-caps": asset0_72,
      "font.rogsansrfstd-bd": asset0_73,
      "font.stone-serif-itc-semi": asset0_74,
    },
    colorPresets: presets0,
    manifest: runtimeManifests[0],
    template: runtimeTemplates[0],
  },
] as const
