import { readFile, rename, writeFile } from "node:fs/promises"
import path from "node:path"

import { catalogRelative, loadCatalog, loadCatalogDefaults, packageDirectory } from "./catalog.mjs"

const entries = await loadCatalog()
const defaults = await loadCatalogDefaults()
const imports = []
const importCollator = new Intl.Collator("en", { numeric: true, sensitivity: "base" })

function importSortKey(specifier) {
  return specifier.replace(/[./_-]/g, (character) => {
    if (character === ".") return "_"
    if (character === "/") return "-"
    if (character === "_") return "."
    return "/"
  })
}

function compareImports(left, right) {
  const leftKey = importSortKey(left.specifier)
  const rightKey = importSortKey(right.specifier)
  return (
    importCollator.compare(leftKey, rightKey) ||
    (leftKey < rightKey ? -1 : leftKey > rightKey ? 1 : 0)
  )
}

function addImport(name, specifier) {
  imports.push({ name, specifier })
}

function sourceRelative(file) {
  return `../${catalogRelative(file).split(path.sep).join("/")}`
}

const generatedEntries = entries.map((entry, entryIndex) => {
  let presetsExpression = "{}"
  if (entry.colorPresetsFile) {
    const presetsName = `presets${entryIndex}`
    addImport(presetsName, sourceRelative(entry.colorPresetsFile))
    presetsExpression = presetsName
  }

  const assetEntries = Object.entries(entry.assetFiles).map(([id, file], assetIndex) => {
    const assetName = `asset${entryIndex}_${assetIndex}`
    addImport(assetName, `${sourceRelative(file)}?url`)
    return `      ${JSON.stringify(id)}: ${assetName},`
  })

  return [
    "  {",
    "    assets: {",
    ...assetEntries,
    "    },",
    `    colorPresets: ${presetsExpression},`,
    `    manifest: runtimeManifests[${entryIndex}],`,
    `    template: runtimeTemplates[${entryIndex}],`,
    "  },",
  ].join("\n")
})

const output = [
  "// Generated by scripts/generate-runtime.mjs. Do not edit by hand.",
  ...imports
    .sort(compareImports)
    .map(({ name, specifier }) => `import ${name} from ${JSON.stringify(specifier)}`),
  "",
  'import runtimeManifests from "./generated-runtime-manifests.json"',
  'import runtimeTemplates from "./generated-runtime-templates.json"',
  "",
  `export const generatedDefaultTemplateIds = { ${Object.entries(defaults)
    .map(([kind, id]) => `${kind}: ${JSON.stringify(id)}`)
    .join(", ")} } as const`,
  "",
  "export const generatedTemplateEntries = [",
  ...generatedEntries,
  "] as const",
  "",
].join("\n")

const destination = path.join(packageDirectory, "src/generated-catalog.ts")
const manifestDestination = path.join(packageDirectory, "src/generated-runtime-manifests.json")
const templateDestination = path.join(packageDirectory, "src/generated-runtime-templates.json")
const temporary = `${destination}.tmp`
const manifestTemporary = `${manifestDestination}.tmp`
const templateTemporary = `${templateDestination}.tmp`
const manifestOutput = `${JSON.stringify(
  entries.map((entry) => entry.runtimeManifest),
  null,
  2,
)}\n`
const templateOutput = `${JSON.stringify(
  entries.map((entry) => entry.template),
  null,
  2,
)}\n`

if (process.argv.includes("--check")) {
  const [currentCatalog, currentManifests, currentTemplates] = await Promise.all([
    readFile(destination, "utf8"),
    readFile(manifestDestination, "utf8"),
    readFile(templateDestination, "utf8"),
  ])
  if (
    currentCatalog !== output ||
    currentManifests !== manifestOutput ||
    currentTemplates !== templateOutput
  ) {
    throw new Error(
      "Generated template catalog is stale; run pnpm generate:catalog from the repository root.",
    )
  }
  console.log(`Verified ${entries.length} generated template imports`)
} else {
  await writeFile(temporary, output)
  await writeFile(manifestTemporary, manifestOutput)
  await writeFile(templateTemporary, templateOutput)
  await rename(temporary, destination)
  await rename(manifestTemporary, manifestDestination)
  await rename(templateTemporary, templateDestination)
  console.log(`Generated ${entries.length} template imports`)
}
